edition = "2018"
version = "Two"
disable_all_formatting = false
ignore = []

indent_style = "Block"
use_small_heuristics = "Default"
binop_separator = "Front"
combine_control_expr = true
comment_width = 110
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
error_on_line_overflow = false
error_on_unformatted = false
fn_args_density = "Tall"
brace_style = "PreferSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_single_line = false
where_single_line = true
force_explicit_abi = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = true
match_block_trailing_comma = false
max_width = 110
merge_derives = true
force_multiline_blocks = true
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = true
struct_lit_single_line = true
tab_spaces = 2
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = ture
wrap_comments = true
match_arm_blocks = false
overflow_delimited_expr = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
hide_parse_errors = false
color = "Auto"
unstable_features = "true"
license_template_path = ""
normalize_doc_attributes = true
