add_newline = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"

[directory]
truncation_length = 8
style = "bold magenta"

[character]
symbol = "Î»"
vicmd_symbol = "Â·"
style_success = "bold purple"
style_failure = "bold purple"
use_symbol_for_status = false

[memory_usage]
disabled = true

[git_branch]
style = "bold red"

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
cherry_pick = "ğŸ’"
rebase = "âš "
merge = "ïƒ¨ "

[git_status]
prefix = ""
suffix = ""

[rust]
prefix = ""
suffix = ""
