add_newline = false

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"

[directory]
truncation_length = 8
style = "purple"

[character]
symbol = "Î»"
vicmd_symbol = "ïŠ‹"
style_success = "blue"
style_failure = "magenta"
use_symbol_for_status = false

[memory_usage]
disabled = false
show_percentage = true
show_swap = false
threshold = -1
symbol = "ï‹› "
separator = ", "
style = "bold green"

[git_commit]
disabled = false
commit_hash_length = 4

[git_state]
cherry_pick = "ğŸ’"
rebase = "âš"
merge = "ïƒ¨"

[git_status]
deleted = "ï„­ "
untracked = "ï™ "
stashed = "ïƒ‡ "
modified = "ïª "
prefix = ""
suffix = ""
